# Generated by Django 5.2.5 on 2025-08-16 06:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_volume',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_winnings',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
