# Generated by Django 5.2.5 on 2026-01-06 18:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0002_referralprofile_referraltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralprofile',
            name='active_referrals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referralprofile',
            name='deposit_earnings',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='referralprofile',
            name='signup_earnings',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='referralprofile',
            name='tier',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('diamond', 'Diamond'), ('platinum', 'Platinum')], default='bronze', max_length=20),
        ),
        migrations.AddField(
            model_name='referralprofile',
            name='tier_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referralprofile',
            name='total_referral_volume',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='referralprofile',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referralprofile',
            name='trading_earnings',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='referralprofile',
            name='withdrawal_earnings',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='referraltransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='referraltransaction',
            name='source_transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referraltransaction',
            name='xp_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referraltransaction',
            name='transaction_type',
            field=models.CharField(choices=[('signup', 'Signup Bonus'), ('deposit', 'Deposit Commission'), ('withdrawal', 'Withdrawal Commission'), ('first_bet', 'First Bet Bonus'), ('bet', 'Bet Commission'), ('tier_upgrade', 'Tier Upgrade')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='referralprofile',
            index=models.Index(fields=['referral_code'], name='acounts_ref_referra_7bf634_idx'),
        ),
        migrations.AddIndex(
            model_name='referralprofile',
            index=models.Index(fields=['tier', '-total_xp'], name='acounts_ref_tier_4eb9dc_idx'),
        ),
        migrations.AddIndex(
            model_name='referralprofile',
            index=models.Index(fields=['-active_referrals'], name='acounts_ref_active__695fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='referraltransaction',
            index=models.Index(fields=['referrer', '-created_at'], name='acounts_ref_referre_083fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='referraltransaction',
            index=models.Index(fields=['transaction_type'], name='acounts_ref_transac_7462ed_idx'),
        ),
    ]
