# Generated by Django 5.2.5 on 2025-08-16 06:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=15)),
                ('odds_at_bet', models.DecimalField(decimal_places=4, max_digits=8)),
                ('potential_payout', models.DecimalField(decimal_places=6, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('won', 'Won'), ('lost', 'Lost'), ('refunded', 'Refunded')], default='active', max_length=20)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('actual_payout', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('fees_paid', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='market.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='market.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bet', 'Bet Placed'), ('payout', 'Payout'), ('refund', 'Refund'), ('fee', 'Fee')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('balance_before', models.DecimalField(decimal_places=6, max_digits=20)),
                ('balance_after', models.DecimalField(decimal_places=6, max_digits=20)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='predict.bet')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bets', models.IntegerField(default=0)),
                ('active_bets', models.IntegerField(default=0)),
                ('won_bets', models.IntegerField(default=0)),
                ('lost_bets', models.IntegerField(default=0)),
                ('total_wagered', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('total_winnings', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('net_profit', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('win_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('roi', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('markets_created', models.IntegerField(default=0)),
                ('creator_fees_earned', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', '-placed_at'], name='predict_bet_user_id_740822_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['market', 'outcome'], name='predict_bet_market__671d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['status'], name='predict_bet_status_97a859_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='predict_tra_user_id_01d1af_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='predict_tra_transac_60ebae_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['blockchain_tx_hash'], name='predict_tra_blockch_0e60c7_idx'),
        ),
    ]
