# Generated by Django 5.2.5 on 2025-09-07 08:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bet_type', models.CharField(choices=[('regular', 'Regular Bet'), ('quick', 'Quick Bet')], default='regular', max_length=10)),
                ('outcome', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('FLAT', 'Flat')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=15)),
                ('odds_at_bet', models.DecimalField(decimal_places=4, max_digits=8)),
                ('potential_payout', models.DecimalField(decimal_places=6, max_digits=20)),
                ('round_number', models.IntegerField(default=1)),
                ('round_start_price', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('round_end_price', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('won', 'Won'), ('lost', 'Lost'), ('refunded', 'Refunded')], default='active', max_length=20)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('actual_payout', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('fees_paid', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='market.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='market.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('impact_level', models.CharField(choices=[('high', 'High Impact'), ('medium', 'Medium Impact'), ('low', 'Low Impact')], max_length=10)),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('related_markets', models.ManyToManyField(blank=True, to='market.market')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bet', 'Bet Placed'), ('payout', 'Payout'), ('refund', 'Refund'), ('fee', 'Fee'), ('bonus', 'Bonus')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('balance_before', models.DecimalField(decimal_places=6, max_digits=20)),
                ('balance_after', models.DecimalField(decimal_places=6, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='predict.bet')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bets', models.IntegerField(default=0)),
                ('active_bets', models.IntegerField(default=0)),
                ('won_bets', models.IntegerField(default=0)),
                ('lost_bets', models.IntegerField(default=0)),
                ('total_wagered', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('total_winnings', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('net_profit', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('win_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('roi', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('current_win_streak', models.IntegerField(default=0)),
                ('longest_win_streak', models.IntegerField(default=0)),
                ('markets_created', models.IntegerField(default=0)),
                ('creator_fees_earned', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('network', models.CharField(choices=[('ethereum', 'Ethereum (ERC-20)'), ('bsc', 'Binance Smart Chain (BEP-20)'), ('polygon', 'Polygon (MATIC)'), ('bitcoin', 'Bitcoin')], max_length=20)),
                ('label', models.CharField(default='My Wallet', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', '-placed_at'], name='predict_bet_user_id_740822_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['market', 'outcome'], name='predict_bet_market__671d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['status', 'round_number'], name='predict_bet_status_8569d4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='predict_tra_user_id_01d1af_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status'], name='predict_tra_transac_00444b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['stripe_payment_intent_id'], name='predict_tra_stripe__0ed3b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='walletaddress',
            unique_together={('user', 'address', 'network')},
        ),
    ]
