# Generated by Django 5.2.5 on 2025-09-06 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_economicevent_rename_no_volume_market_down_volume_and_more'),
        ('predict', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('impact_level', models.CharField(choices=[('high', 'High Impact'), ('medium', 'Medium Impact'), ('low', 'Low Impact')], max_length=10)),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('network', models.CharField(choices=[('ethereum', 'Ethereum (ERC-20)'), ('bsc', 'Binance Smart Chain (BEP-20)'), ('polygon', 'Polygon (MATIC)'), ('bitcoin', 'Bitcoin')], max_length=20)),
                ('label', models.CharField(default='My Wallet', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='bet',
            name='predict_bet_status_97a859_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='predict_tra_transac_60ebae_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='predict_tra_blockch_0e60c7_idx',
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(choices=[('regular', 'Regular Bet'), ('quick', 'Quick Bet')], default='regular', max_length=10),
        ),
        migrations.AddField(
            model_name='bet',
            name='round_end_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bet',
            name='round_start_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userstats',
            name='current_win_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='longest_win_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bet',
            name='outcome',
            field=models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('FLAT', 'Flat')], max_length=4),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bet', 'Bet Placed'), ('payout', 'Payout'), ('refund', 'Refund'), ('fee', 'Fee'), ('bonus', 'Bonus')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['status', 'round_number'], name='predict_bet_status_8569d4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status'], name='predict_tra_transac_00444b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['stripe_payment_intent_id'], name='predict_tra_stripe__0ed3b5_idx'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='related_markets',
            field=models.ManyToManyField(blank=True, to='market.market'),
        ),
        migrations.AddField(
            model_name='walletaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='walletaddress',
            unique_together={('user', 'address', 'network')},
        ),
    ]
