# Generated by Django 5.2.5 on 2025-08-16 06:37

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptocurrencyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('bitcoin', 'Bitcoin (BTC)'), ('ethereum', 'Ethereum (ETH)'), ('altcoins', 'Altcoins'), ('defi', 'DeFi Tokens'), ('nft', 'NFT Collections'), ('memecoins', 'Meme Coins'), ('stablecoins', 'Stablecoins'), ('layer1', 'Layer 1 Blockchains'), ('layer2', 'Layer 2 Solutions'), ('exchanges', 'Exchange Tokens'), ('gaming', 'Gaming Tokens'), ('metaverse', 'Metaverse Tokens'), ('ai', 'AI Tokens'), ('privacy', 'Privacy Coins'), ('governance', 'DAO Governance'), ('general', 'General Crypto')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='₿', max_length=10)),
                ('color_code', models.CharField(default='#F7931A', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cryptocurrency Categories',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('min_bet', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('max_bet', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_date', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('winning_outcome', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10, null=True)),
                ('total_volume', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('yes_volume', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('no_volume', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('creator_fee_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.0200'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('0.1000'))])),
                ('platform_fee_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('0.0500'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='market.cryptocurrencycategory')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_markets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='market_mark_status_1ef6c3_idx'), models.Index(fields=['category', '-total_volume'], name='market_mark_categor_f045b5_idx'), models.Index(fields=['resolution_date'], name='market_mark_resolut_f3adfe_idx')],
            },
        ),
    ]
