# Generated by Django 5.2.5 on 2025-09-07 08:36

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptocurrencyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('bitcoin', 'Bitcoin (BTC)'), ('ethereum', 'Ethereum (ETH)'), ('altcoins', 'Altcoins'), ('defi', 'DeFi Tokens'), ('nft', 'NFT Collections'), ('memecoins', 'Meme Coins'), ('stablecoins', 'Stablecoins'), ('layer1', 'Layer 1 Blockchains'), ('layer2', 'Layer 2 Solutions'), ('exchanges', 'Exchange Tokens'), ('gaming', 'Gaming Tokens'), ('metaverse', 'Metaverse Tokens'), ('ai', 'AI Tokens'), ('privacy', 'Privacy Coins'), ('governance', 'DAO Governance'), ('general', 'General Crypto')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='₿', max_length=10)),
                ('color_code', models.CharField(default='#F7931A', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cryptocurrency Categories',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('cpi', 'Consumer Price Index'), ('fomc', 'Federal Open Market Committee'), ('nfp', 'Non-Farm Payrolls'), ('gdp', 'GDP Release'), ('unemployment', 'Unemployment Data'), ('retail_sales', 'Retail Sales')], max_length=20)),
                ('impact_level', models.CharField(choices=[('high', 'High Impact'), ('medium', 'Medium Impact'), ('low', 'Low Impact')], max_length=10)),
                ('description', models.TextField()),
                ('scheduled_time', models.DateTimeField()),
                ('actual_time', models.DateTimeField(blank=True, null=True)),
                ('expected_value', models.CharField(blank=True, max_length=50)),
                ('actual_value', models.CharField(blank=True, max_length=50)),
                ('previous_value', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('market_type', models.CharField(choices=[('event', 'Economic Event'), ('price', 'Price Prediction'), ('quick', 'Quick Predict')], default='price', max_length=10)),
                ('base_currency', models.CharField(default='BTC', max_length=10)),
                ('quote_currency', models.CharField(default='USDT', max_length=10)),
                ('min_bet', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('max_bet', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_date', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('round_duration', models.IntegerField(default=900)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('winning_outcome', models.CharField(blank=True, choices=[('UP', 'Up'), ('DOWN', 'Down'), ('FLAT', 'Flat')], max_length=10, null=True)),
                ('total_volume', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('up_volume', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('down_volume', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('flat_volume', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('current_round', models.IntegerField(default=1)),
                ('round_start_time', models.DateTimeField(blank=True, null=True)),
                ('round_start_price', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('creator_fee_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.0200'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('0.1000'))])),
                ('platform_fee_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('0.0500'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='market.cryptocurrencycategory')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_markets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='market_mark_status_1ef6c3_idx'), models.Index(fields=['category', '-total_volume'], name='market_mark_categor_f045b5_idx'), models.Index(fields=['resolution_date'], name='market_mark_resolut_f3adfe_idx'), models.Index(fields=['market_type', 'status'], name='market_mark_market__c15206_idx')],
            },
        ),
    ]
