# Generated by Django 5.2.5 on 2026-01-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='market_type',
            field=models.CharField(choices=[('event', 'Economic Event'), ('price', 'Price Prediction'), ('quick', 'Quick Predict'), ('target', 'Price Target')], default='price', max_length=10),
        ),
    ]
