# Generated by Django 5.2.5 on 2025-09-06 06:38

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('cpi', 'Consumer Price Index'), ('fomc', 'Federal Open Market Committee'), ('nfp', 'Non-Farm Payrolls'), ('gdp', 'GDP Release'), ('unemployment', 'Unemployment Data'), ('retail_sales', 'Retail Sales')], max_length=20)),
                ('impact_level', models.CharField(choices=[('high', 'High Impact'), ('medium', 'Medium Impact'), ('low', 'Low Impact')], max_length=10)),
                ('description', models.TextField()),
                ('scheduled_time', models.DateTimeField()),
                ('actual_time', models.DateTimeField(blank=True, null=True)),
                ('expected_value', models.CharField(blank=True, max_length=50)),
                ('actual_value', models.CharField(blank=True, max_length=50)),
                ('previous_value', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.RenameField(
            model_name='market',
            old_name='no_volume',
            new_name='down_volume',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='yes_volume',
            new_name='flat_volume',
        ),
        migrations.AddField(
            model_name='market',
            name='base_currency',
            field=models.CharField(default='BTC', max_length=10),
        ),
        migrations.AddField(
            model_name='market',
            name='current_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='market',
            name='market_type',
            field=models.CharField(choices=[('event', 'Economic Event'), ('price', 'Price Prediction'), ('quick', 'Quick Predict')], default='price', max_length=10),
        ),
        migrations.AddField(
            model_name='market',
            name='quote_currency',
            field=models.CharField(default='USDT', max_length=10),
        ),
        migrations.AddField(
            model_name='market',
            name='round_duration',
            field=models.IntegerField(default=900),
        ),
        migrations.AddField(
            model_name='market',
            name='round_start_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='round_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='up_volume',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='market',
            name='winning_outcome',
            field=models.CharField(blank=True, choices=[('UP', 'Up'), ('DOWN', 'Down'), ('FLAT', 'Flat')], max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['market_type', 'status'], name='market_mark_market__c15206_idx'),
        ),
    ]
