# Generated by Django 5.2.5 on 2026-01-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_add_target_market_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='highest_price_reached',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Highest price reached during market lifetime (for target markets)', max_digits=15, null=True),
        ),
    ]
