"""
Django settings for evgwork project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

from urllib.parse import urlparse
from decimal import Decimal
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY= os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG')

ALLOWED_HOSTS = ['www.evgxchain.com','evgxchain.com']
# ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'acounts',
    'market',
    'predict',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'evgwork.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'evgwork.wsgi.application'

AUTH_USER_MODEL = 'acounts.CustomUser'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv("MAILTRAP_HOST")
EMAIL_PORT = os.getenv("MAILTRAP_PORT")
EMAIL_USE_TLS = os.getenv("MAILTAP_USE_TLS")   
EMAIL_HOST_USER = os.getenv("MAILTRAP_USERNAME")  
EMAIL_HOST_PASSWORD = os.getenv("MAILTRAP_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")


COINREMITTER_API_KEY = os.getenv("COINREMITTER_API_KEY") 
COINREMITTER_PASSWORD = os.getenv("COINREMITTER_WALLET_PASSWORD")
COINREMITTER_USDT_COIN = 'USDT' 

# Production settings (when COINREMITTER_TESTING_MODE = False)
# COINREMITTER_DEFAULT_NETWORK = 'trc20'  # or 'erc20'

WITHDRAWAL_FEE_PERCENTAGE = Decimal('0.02')
if DEBUG:
    COINREMITTER_TESTING_MODE = True  
else:
    COINREMITTER_TESTING_MODE = False  

COINREMITTER_TESTING_MODE = os.getenv('COINREMITTER_TESTING_MODE')
TCN_BYPASS_ADDRESS_VALIDATION = os.getenv('TCN_BYPASS_ADDRESS_VALIDATION')

# Site URL for email links
SITE_URL = os.getenv('SITE_URL', 'https://www.evgxchain.com')

LOGIN_URL = 'login-page'

DEFAULT_FROM_EMAIL=os.getenv('DEFAULT_FROM_EMAIL')
SERVER_EMAIL = DEFAULT_FROM_EMAIL
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# db_url = urlparse(os.getenv('DATABASE_URL'))

import dj_database_url


if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASS'),
            'HOST': os.getenv("DB_URL"),
            'PORT': os.getenv('DB_PORT')
        }
    }



STRIPE_PUBLISHABLE_KEY=os.getenv('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY=os.getenv('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET=os.getenv('STRIPE_WEBHOOK_SECRET')

B2BINPAY_WALLETS = {
    'BTC': os.getenv('B2BINPAY_BTC_WALLET_ID', default=''),
    'ETH': os.getenv('B2BINPAY_ETH_WALLET_ID', default=''),
    'USDT': os.getenv('B2BINPAY_USDT_WALLET_ID', default='479'),  
    'LTC': os.getenv('B2BINPAY_LTC_WALLET_ID', default=''),
    'TRX': os.getenv('B2BINPAY_TRX_WALLET_ID', default=''),
}

MIN_DEPOSIT_AMOUNT = Decimal('10.00')
MAX_DEPOSIT_AMOUNT = Decimal('50000.00')
MIN_WITHDRAWAL_AMOUNT = Decimal('20.00')
MAX_WITHDRAWAL_AMOUNT = Decimal('50000.00')

B2BINPAY_CLIENT_ID = os.getenv('B2BINPAY_CLIENT_ID', default='')
B2BINPAY_CLIENT_SECRET = os.getenv('B2BINPAY_CLIENT_SECRET', default='')
B2BINPAY_CALLBACK_SECRET = os.getenv('B2BINPAY_CALLBACK_SECRET', default='')

B2BINPAY_BASE_URL = os.getenv('B2BINPAY_BASE_URL', default='https://v3.api-sandbox.b2binpay.com')

REFERRAL_BONUS_AMOUNT = 10.00
REFERRAL_SIGNUP_BONUS = 5.00   

WITHDRAWAL_FEE_PERCENTAGE = Decimal('0.02')  
WITHDRAWAL_NETWORK_FEE = Decimal('2.00') 

LOG_FILE_PATH = os.path.join(BASE_DIR, 'debug.log')


try:
    with open(LOG_FILE_PATH, 'a') as f:
        f.write('')  
except Exception as e:
    LOG_FILE_PATH = os.path.join('/tmp', 'debug.log')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',  # Set to DEBUG to catch everything
            'class': 'logging.FileHandler',
            'filename': LOG_FILE_PATH,
            'formatter': 'verbose',
            'mode': 'a',  # Append mode
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        '': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        # Make sure Django logs also go to file
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

SCHEDULER_CONFIG = {
    'apscheduler.jobstores.default': {
        'type': 'memory'
    },
    'apscheduler.executors.default': {
        'class': 'apscheduler.executors.pool:ThreadPoolExecutor',
        'max_workers': '5'
    },
    'apscheduler.executors.processpool': {
        'type': 'processpool',
        'max_workers': '3'
    },
    'apscheduler.job_defaults.coalesce': 'false',
    'apscheduler.job_defaults.max_instances': '1',
    'apscheduler.timezone': 'UTC',
}

SCHEDULER_AUTOSTART = True


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'),]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
